kind: Kustomization
bases:
  - ../../base
resources:
  - trusted-ca.yaml   

patchesJson6902:
  - path: jupyterhub-dc.yaml
    target:
      group: apps
      version: v1
      kind: DeploymentConfig
      name: jupyterhub
